### ISSUE TITLE
Virtual Machine with pre-installed qWAT

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#131]
It would be great to be able to distribute a Virtual Machine with a pre-installed qWAT solution, for testing and evaluation purposes.

It could be based on OSGeo-Live

**Comment by tudorbarascu** [comment]
I can create and host a VM that does exactly that. I'm already doing it for the [qgep project ](http://qgep.github.io/docs/admin-guide/vm/index.html) so it wouldn't be such a bother.
Actually, I think it would be nice to have just one machine for the two projects.
I am using Debian with Cinnamon as Desktop as Cinnamon is more friendly towards new users.
My plans include adding Web Services in the mix  so that new users see the possibilities (in the current vm there is a working Qgis Web Client setup with qgep as a project).
Thoughts?

**Comment by vpicavet** [comment]
Having a Vagrantfile for automated VM building would be ideal, so we can push it to the repo, and have an updated VM easily. It would also help keeping the VM as small as possible.

Do not hesitate to assign yourself the task if you feel like doing it.

**Comment by tudorbarascu** [comment]
I'll do it.
As I don't have experience with vagrant for now I'll simply make a vm and work towards the ideal case as I'm learning vagrant.
It seems I cannot assign myself to any issue but consider me assigned.

**Comment by vpicavet** [comment]
If you install on a VM, please take notes on all required steps, this can be a good basis for the installation page of the documentation ( see wiki).

**Comment by tudorbarascu** [comment]
Will do.
I think that for the long run it would be better if we would make a separate repo for the docs.

**Comment by tudorbarascu** [comment]
Fixed in https://github.com/qwat/QWAT/commit/e571d5564d004bcc75b24dc97f548ab1e9376f3a
