### ISSUE TITLE
Bugs when use the widget "reference value" with the 2 or more filters and the active option "Chain filters"

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#186]
For the form of layers "pipe" and "valve", we have set a "relation value" widget for the choice of material, diameter options on the feature. 
When we use the widget relation value with 2 or more filters and active the "chain Filters" option, the values proposed in the last drop-down list ignore the previous choices (previous filters). 

For the example and to test , I put a project here : [https://share.oslandia.net/public/7c490a](https://share.oslandia.net/public/7c490a)
We can see also the demo here : [https://share.oslandia.net/public/279b3e](https://share.oslandia.net/public/279b3e)

**Comment by dsavary** [comment]
@haubourg these bugs can be fix for QGIS 2.18 ?

**Comment by dsavary** [comment]
Planned for june/july on QGIS 2.xx LTR ?

**Comment by haubourg** [comment]
yep

**Comment by pblottiere** [comment]
@haubourg 

I'm not sure to have fully understand the issue here. I think it's fixed in this branch : https://github.com/pblottiere/QGIS/tree/bugfix_chainfilter

Can you take a look to validate the behavior? Then I'll write unit tests and I'll propose a PR.

Moreover, I did not find any related ticket on https://issues.qgis.org/issues/. Perhaps I missed it. 

Thank you ;)

**Comment by haubourg** [comment]
I think there was no ticket upstream due to the difficulty to describe what exactly the issue was. 

@dsavary Paul found that the cache of filters between values was build only comparing the neighbor field, which leaded to inconsistencies in the real filtered list when playing with three fields. 
Can you reformulate the exact problem to see if we fixed it well?

**Comment by pblottiere** [comment]
@dsavary Here a screenshot coming from the GIF given above:

![chainfilter0](https://user-images.githubusercontent.com/9266424/28366513-f5c35b66-6c84-11e7-87bc-0971877983df.png)

From what I understand, the last combo box should NOT propose **brides** or **manchon** because there no corresponding feature with the full filter expression *"diameter" = '120' AND "material_value" = 'fer' AND "raccord_value" = 'brides'*. 

The combo box should only propose **collier** in this case. Am I right?

**Comment by dsavary** [comment]
@haubourg @pblottiere Yes exactly. only the value "collier" must be proposed. the widget don't take into account the 2 first combo box only the previous combo box.

**Comment by pblottiere** [comment]
Ok, so that's well what I fixed :). I let you know about the PR soon.

@dsavary Thank you for the confirmation!

**Comment by dsavary** [comment]
@pblottiere  Cool ! Thanks for the job.

**Comment by pblottiere** [comment]
I created a QGIS bug report for this issue : https://issues.qgis.org/issues/16903

**Comment by pblottiere** [comment]
@dsavary At the moment I'm writing unit tests. So the PR is coming very soon ;)

**Comment by pblottiere** [comment]
A PR has been proposed : https://github.com/qgis/QGIS/pull/4904

**Comment by haubourg** [comment]
fixed in https://issues.qgis.org/projects/qgis/repository/revisions/8642e88867c5be212f49d73fd3f3f4ce96b0dc61

**Comment by pblottiere** [comment]
The PR has been merged indeed. I'm working on the backport.

**Comment by pblottiere** [comment]
During the backport, I noticed a strange behavior when filters are reset. 

So I made another PR to fix it. I'm waiting for this last PR to be merged before doing the backport.

**Comment by pblottiere** [comment]
Second PR has been merged.

**Comment by pblottiere** [comment]
A PR for the backport is launched.

**Comment by pblottiere** [comment]
Backport is merged

**Comment by dsavary** [comment]
Tested with QGIS 2.18.12. It works well.
Thanks
