### ISSUE TITLE
Widget constraints - performance and usability issues

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#217]
Hi,

Trying to go all in with the constraints on forms (drag&drop), for valves at least, I'm encountering serious performance issues, around 17 seconds until the form shows when using add new feature tool.
If I untick the "Not null" constraint for all the the needed fields (5 in total) the add new feature form pops out at around 3 seconds, which is usable.

Also, for "Text edit" widgets I don't see the red background for fields that don't respect the constraints, as I see for combo-boxes. I remember that it worked before, so it's probably a regression. I'm under Debian, QGIS 2.18.11.

Anybody else encountered this?

**Comment by tudorbarascu** [comment]
Actually, it seems the culprit is the combination between drag&drop designer and constraints.

**Comment by haubourg** [comment]
Oh I wasn't aware of thoss issues. Did you raise them in QGIS redmine?

**Comment by tudorbarascu** [comment]
Unfortunately no, I was first waiting for a response to my "Anybody else encountered this?" question. But on the same layer, two styles, one with drag&drop and one with UI files. The difference is very high for a layer with lots of columns/widgets. Will try and make a test project with geopackage in the following weeks.

**Comment by ponceta** [comment]
@tudorbarascu @Pully we dropped ui forms in favor of drag and drop forms a few months ago.

I also dropped all unused relations (which were slowing the form opening, sometimes drastically)

@3nids was surprised that it had such an impact on performance.

Regarding constraints, we are actually not using theses for qwat, since many constraints are already provided from the database and there are only one or two people editing for our water network. We are using these for qgep with drag and drop forms but qgep is generally a bit slower.

![image](https://user-images.githubusercontent.com/8614223/31874338-ecbdfcc6-b7c8-11e7-9da5-8ed369eb8f6e.png)

**Comment by tudorbarascu** [comment]
@ponceta Thanks for the info.

**Comment by ponceta** [comment]
Still an issue?

**Comment by ponceta** [comment]
@tudorbarascu is it still an issue? Do you have an open issue for this on QGIS Upstream?

**Comment by tudorbarascu** [comment]
I don't know if it's still an issue as I'm still using the workarounds from when  I discovered this. A little time constraint to test right now (it's on my TODO list). No ticket upstream. Sorry for not being helpful for now.

**Comment by ponceta** [comment]
@tudorbarascu it would be nice to provide the upstream community (QGIS) if this issue is still relevant on latest releases of QGIS.

**Comment by tudorbarascu** [comment]
I cannot replicate anymore.

**Comment by ponceta** [comment]
Good to know that QGIS 3.16 comes even better in terms of stability!
