### ISSUE TITLE
Huge symbole size in the layer tree legend of a QGIS projet 

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#234]
When you use for the layer style : 

- units map for the symbol size
- simple symbol or SVG symbol
- Zoom to scale : < 1: 10 (very little scale) 

The symbole size doesn't remain fixed and appears huge when you zoom in .
regression in QGIS 2.18 or normal behaviour ? 
similar issue QGIS closed : [https://issues.qgis.org/issues/13979](https://issues.qgis.org/issues/13979)

If the symbole size is in units "millimeter" , no problem appears and the symbole size in the layer legend remains fixed. 

![huge_symbole_size](https://user-images.githubusercontent.com/6229296/31769473-16f6daf0-b4d4-11e7-8733-8dbd23810370.png)

![huge_symbole_size_layer_properties](https://user-images.githubusercontent.com/6229296/31769531-5db535e0-b4d4-11e7-88d8-f4e055c4c98a.png)

**Comment by haubourg** [comment]
Oui, c'est le comportement normal depuis la 2.14 je crois. 
Le plus simple est de mettre des taquets de taille max / min pour empêcher de trop grandire dans le bouton avec une clé à molette. 
J'avais essayé de discuter pour mettre des limites à ces tailles, sans réussir à le faire accepter. 

It's the default behavior since 2.14 IIRC. Using scale or size limits in the map units setting dialog is the only way to prevent them to become too big. They will stay inlined with the actual map display

**Comment by dsavary** [comment]
it would be nice if the symbols size in the layer legend (in QGIS project) still remain fixed. Proposal to the QGIS community . :)

**Comment by ponceta** [comment]
Same for QGEP, but not for all?

![image](https://user-images.githubusercontent.com/8614223/32161369-94d515de-bd55-11e7-9fc1-8af4526633a4.png)

**Comment by ponceta** [comment]
Seems to be fixed on QGIS 3.16.X

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/103072669-4cd80a00-45c6-11eb-8659-09c566e014a1.png)

The symbol is now truncated if too large to be displayed in the legend.
