### ISSUE TITLE
Chain filters cannot select NULL values

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#237]
When using chain filters, it's not possible to select a material that has a NULL diameter.

This means the "Other", "Unknown", "To be determined" values and all the materials without Diameter cannot be selected.

The combinations between material and NULL diameter are unique, so it should have worked.

![bug](https://user-images.githubusercontent.com/3179646/33113603-cdbb8a22-cf61-11e7-9303-6eed66da46d9.jpg)

A solution is to add empty string in the Diameter part and the user can select the empty string.
I can make a pull request in the data model but I think this should be fixed in the widget.

**Comment by haubourg** [comment]
@pblottiere any opinion here?

**Comment by 3nids** [comment]
I think it's a good solution to add empty or strings like "unknown" in diameter column.
There is already on unknow diameter per material type to handle such situations.

**Comment by ponceta** [comment]
3.14.0 seems to fix this, as soon as you have a valid Null diameter entity for your material :

![Materials](https://user-images.githubusercontent.com/8614223/85398589-c2024e00-b555-11ea-9667-9c13752030fc.gif)

Otherwise it will take the first diameter available (that's why a check that every material has a Null diameter instance should be checked)

**Comment by ponceta** [comment]
@tudorbarascu this seems to be solved to me, please feel to reopen if needed.
