### ISSUE TITLE
Dynamic link on hydrant for hinni system

### ISSUE THREAD

**Issue by varrieta** [qwat/QWAT#262]
For Hinni hydrants, we have to integrate an URL linking to the Hinni system. The URL is made of a static part, the link, and a dynamic part, the identifier of the hydrant. 

Does anyone else have to deal with Hinni hydrants links?

**Comment by varrieta** [comment]
Since the link doesn't need to be saved in the database, I use a qgs open action to create and then open the URL. Simple and efficient, if anyone needs to do the same.

**Comment by ponceta** [comment]
On my side I added to that a virtual field with external ressource as attribute type and active url.

![image](https://user-images.githubusercontent.com/8614223/38605289-25bc08da-3d73-11e8-88c4-53f48fcdd7dc.png)

I had to remove space characters (that's why regex_replace):

`regexp_replace(concat( 'https://kontrollsysteme.hinni.ch/dbhvista/?mkey=****MySecureKey****&ShowEntityDesignation=', "identification" ),' ','')`

This is then directly accessible from the hydrant form.

For the python script action :

![image](https://user-images.githubusercontent.com/8614223/38605724-6860f12c-3d74-11e8-8490-23fa64ed9921.png)

```
https://kontrollsysteme.hinni.ch/dbhvista/?mkey=****MyPrivateKey****&ShowEntityDesignation=[%CASE
	WHEN length("identification") > 3 THEN replace("identification", ' ' ,'')
	ELSE left("identification",1) || '0' || right("identification",1)
END%]&et=1
```

This could be somewhere documented as it is a common use case at least in switzerland.

**Comment by haubourg** [comment]
Why not add some Hinni valves in the demo dataset , propose a QML example somewhere and a "Tips and tricks" section in the documentation or web site?

**Comment by ponceta** [comment]
Opened a documentation issue. https://github.com/qwat/docs/issues/9
