### ISSUE TITLE
Continuing a pipe will fail with PostGIS backend

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#79]
If we want to continue a pipe, declared as multi-geometry, the "merge entities" feature does not work when the backend is a PostGIS layer.

**Comment by mhugo** [comment]
@3nids Could you be more specific ? What is the geometry type of the layer where the merge is executed ?
I guess it's multilinestringZ right ?

**Comment by 3nids** [comment]
I am not sure what we speak about.
I am not at the origin of the issue.
Not sure, but wasn't it related to a plugin allowing prolongation of linestrings?
Although, we don't have multi line strings in QWAT...
a bit lost here!

**Comment by mhugo** [comment]
Ok. My original understanding was : there is a project with linestrings (no multi) and the user wants to use the "merge selected features" operation from QGIS in order to allow "prolongation". But this "merge" operation is a geometric union and could potentially result in a multi geometry and thus cannot be commited.

So what is the need : to allow the prolongation, thanks to a plugin or a core operation or to fix some bugs with the "merge" operation ?

**Comment by 3nids** [comment]
I think the two issues exist.

For line prolongation, I think the decision was to wait CAD integration, and having this feature integrated in the node tool maybe.

For merging feature, I never tried, but indeed if it results in a multi geom, it should be fixed.

**Comment by mhugo** [comment]
> For line prolongation, I think the decision was to wait CAD integration, and having this feature integrated in the node tool maybe.

Ok, thanks for the clarification

> For merging feature, I never tried, but indeed if it results in a multi geom, it should be fixed.

I've just retested. It works fine with 2D linestrings, but not with geometries with a Z value ...

**Comment by 3nids** [comment]
How come? Will your PR improve this situation?

**Comment by mhugo** [comment]
I am working on the merge of linestringZ issue and will propose a PR for that.

**Comment by mhugo** [comment]
https://github.com/qgis/QGIS/pull/2719
